### ISSUE TITLE
Example not running on iOS, due to issue with ImageUtils.convertYUV420ToImage

### ISSUE THREAD

**Issue by bazinac** [am15h/object_detection_flutter#3]
That is nice example, but it does not run on iOS as ImageUtils.convertYUV420ToImage is failing with

```
2020-09-17 00:03:40.267607+0200 Runner[562:53623] Metal GPU Frame Capture Enabled
2020-09-17 00:03:40.267755+0200 Runner[562:53623] Metal API Validation Enabled
2020-09-17 00:03:40.374333+0200 Runner[562:53885] flutter: Observatory listening on http://127.0.0.1:53498/i9mCuWLFiB0=/
2020-09-17 00:03:40.974505+0200 Runner[562:53874] Initialized TensorFlow Lite runtime.
2020-09-17 00:03:41.344477+0200 Runner[562:53913] [VERBOSE-2:dart_isolate.cc(865)] Unhandled exception:
RangeError (index): Invalid value: Only valid value is 0: 1
#0      List.[] (dart:core-patch/array.dart:180:52)
#1       (package:object_detection/utils/image_utils.dart:14:47)
#2      IsolateUtils.entryPoint (package:object_detection/utils/isolate_utils.dart:41:24)
#3      _RootZone.runUnary (dart:async/zone.dart:1450:54)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#6      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#7      Future._complete (dart:async/future_impl.dart:519:7)
#8      _StreamIterator._onData (dart:async/stream_impl.dart:1070:20)
#9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#12     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#13     _StreamController._add (dart:async/stream_controller.dart:682:7)
#14     _StreamController.add (dart:async/stream_controller.dart:624:5)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
2020-09-17 00:03:43.965199+0200 Runner[562:53874] [VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: CameraException(A camera has started streaming images., startImageStream was called while a camera was streaming images.)
```

Camera preview starts, but it seems that classifier is not obtaining any images due to this... 

EDIT: Ok, I have found that this is caused by the fact that in iOS, cameraImage.format is bgra8888.
and android cameraImage.format, it is yuv420. I will try to provide code that would handle images based on what platform it runs on  and post PR.

**Comment by bazinac** [comment]
@am15h :If you would grant me access to this repository, I would push new branch with proposed solution.

**Comment by cpunion** [comment]
@bazinac You can open a Pull Request.

**Comment by am15h** [comment]
Thanks a lot, @bazinac, for the PR.
